using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using System.Windows.Input;
using TreeNode = LunaForge.Models.TreeNodes.TreeNode;

namespace LunaForge.Helpers;

public class IgnoreCommandsContractResolver : DefaultContractResolver
{
    protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
    {
        JsonProperty property = base.CreateProperty(member, memberSerialization);

        // Ignore ICommand properties (RelayCommand, etc.)
        if (typeof(ICommand).IsAssignableFrom(property.PropertyType))
        {
            property.ShouldSerialize = _ => false;
            return property;
        }

        // Ignore properties ending with "Command" (generated by RelayCommand)
        if (property.PropertyName?.EndsWith("Command", StringComparison.Ordinal) == true)
        {
            property.ShouldSerialize = _ => false;
            return property;
        }

        return property;
    }
}

public static class EditorSerializer
{
    public static readonly JsonSerializerSettings TreeNodeSettings =
        new()
        {
            TypeNameHandling = TypeNameHandling.Auto,
            DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate,
            ContractResolver = new IgnoreCommandsContractResolver(),
            ObjectCreationHandling = ObjectCreationHandling.Replace
        };

    public static string SerializeTreeNode(object o)
    {
        return JsonConvert.SerializeObject(o, typeof(TreeNode), TreeNodeSettings);
    }

    public static object DeserializeTreeNode(string s)
    {
        return JsonConvert.DeserializeObject(s, typeof(TreeNode), TreeNodeSettings);
    }
}